export const REROLL_WINNER_REQUEST = 'REROLL_WINNER_REQUEST'
export const REROLL_WINNER_SUCCESS = 'REROLL_WINNER_SUCCESS'
export const REROLL_WINNER_FAIL = 'REROLL_WINNER_FAIL'

export const EDIT_WINNER_REQUEST = 'EDIT_WINNER_REQUEST'
export const EDIT_WINNER_SUCCESS = 'EDIT_WINNER_SUCCESS'
export const EDIT_WINNER_FAIL = 'EDIT_WINNER_FAIL'