export const GET_TYPES_REQUEST = 'GET_TYPES_REQUEST'
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS'
export const GET_TYPES_FAIL = 'GET_TYPES_FAIL'

export const NEW_TYPE_REQUEST = 'NEW_TYPE_REQUEST'
export const NEW_TYPE_SUCCESS = 'NEW_TYPE_SUCCESS'
export const NEW_TYPE_FAIL = 'NEW_TYPE_FAIL'

export const DELETE_TYPE_REQUEST = 'DELETE_TYPE_REQUEST'
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS'
export const DELETE_TYPE_FAIL = 'DELETE_TYPE_FAIL'

export const EDIT_TYPE_REQUEST = 'EDIT_TYPE_REQUEST'
export const EDIT_TYPE_SUCCESS = 'EDIT_TYPE_SUCCESS'
export const EDIT_TYPE_FAIL = 'EDIT_TYPE_FAIL'